id: P009222
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG17421
  title: འཇིག་རྟེན་པའི་དགོད་བྲ།
  author: ''
  volumes:
    5c3255152018427cb4b1bd9bfd199b19:
      image_group_id: I1KG18003
      title: ''
      volume_number: 1
      total_pages: 204
      base_file: v001.txt
